[package]
authors = ["Jacob Hall <email@jacobhall.net>"]
edition = "2021"
name = "skyway"
version = "0.0.1"

[dependencies]
osmpbf = "0.3.4"
clap = { version = "4.5.10", features = ["derive"] }
indicatif = "0.17.8"
json = "0.12.4"
pest = "2.7.11"
pest_derive = "2.7.11"
