[workspace]
resolver = "3"
members = ["skyway", "skyway-python"]

[workspace.package]
version = "0.7.1"
edition = "2024"
license = "GPL-3.0-or-later"
authors = ["Jacob Hall <email@jacobhall.net>"]
homepage = "https://maprva.github.io/skyway/"
repository = "https://github.com/MapRVA/skyway"

[workspace.dependencies]
skyway = { path = "skyway" }

[profile.release]
lto = "fat"
codegen-units = 1

[profile.profiling]
inherits = "release"
debug = 1
