[package]
name = "osm2memgraph"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rsmgclient = "2.0.2"
osmpbf = "0.2"
clap = { version = "4.4.7", features = ["derive"] }
toml = "0.8.8"
indicatif = "0.17.7"
