[build-system]
requires = ["maturin>=1,<2"]
build-backend = "maturin"

[project]
name = "skyway"
version = "0.7.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]

[tool.maturin]
strip = true
module-name = "skyway"

[tool.uv]
cache-keys = [
    { file = "pyproject.toml" },
    { file = "../**/Cargo.*" },
    { file = "../**/*.rs" },
]
