name: Build

on:
  pull_request:
  push:

env:
  # disable incremental compilation for faster from-scratch builds
  CARGO_INCREMENTAL: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y capnproto
    - run: rustup update
    - run: cargo build
