name: tests

on:
  pull_request:
  push:
    paths:
      - skyway/**
      - Cargo.toml
      - Cargo.lock
      - .github/workflows/test.yml
    branches: [trunk]

jobs:
  test:
    strategy:
      matrix:
        platform:
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-gnu

          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-gnu

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: MacOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin

          - os-name: MacOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          args: --manifest-path skyway/Cargo.toml --features "reqwest/rustls-tls"
          target: ${{ matrix.platform.target }}
      - name: Build binary (no features)
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          args: --no-default-features --manifest-path skyway/Cargo.toml
          target: ${{ matrix.platform.target }}
      - name: Run tests
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: test
          args: --manifest-path skyway/Cargo.toml --features "reqwest/rustls-tls"
          use-rust-cache: false
          target: ${{ matrix.platform.target }}
